volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  static_volume: {}
  production_traefik: {}
  


services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: sw_task_production_django
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sw_task_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.env

  redis:
    image: docker.io/redis:6
    
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: sw_task_production_nginx
    container_name: sw_task_production_nginx
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - ./compose/production/nginx/ssl:/etc/nginx/ssl
